
class Json {
  static const json = [
    {
      'id':"1",
      'name': "Dipak Thapa Magar",
      'day': "Yesterday",
      'time': "11:11 PM",
      'status': "I am well. I am well. I am well. I am well. I am well. I am well. I am well. I am well. ",
      'image': "https://cdn.inquisitr.com/wp-content/uploads/2020/01/One-Piece-Straw-Hat-Pirates-bounties-1.jpg",
      'likes': 0,
      'comment': 0,
      'shares': 0,
    },
    {
      'id':"2",
      'name': "David Prakash Mukhiya",
      'day': "Yesterday",
      'time': "11:11 PM",
      'status': "God bless me God bless me God bless me God bless me God bless me God bless me God bless me ",
      'image': "https://cdn.inquisitr.com/wp-content/uploads/2020/01/One-Piece-Straw-Hat-Pirates-bounties-1.jpg",
      'likes': 0,
      'comment': 0,
      'shares': 0,
    },
    {
      'id':"3",
      'name': "Ajay Kunwar",
      'day': "Yesterday",
      'time': "11:11 PM",
      'status': "I am sick I am sick I am sick I am sick I am sick I am sick I am sick I am sick I am sick ",
      'image': "https://cdn.inquisitr.com/wp-content/uploads/2020/01/One-Piece-Straw-Hat-Pirates-bounties-1.jpg",
      'likes': 0,
      'comment': 0,
      'shares': 0,
    },
    {
      'id':"4",
      'name': "Chamkilo",
      'day': "Yesterday",
      'time': "11:11 PM",
      'status': "I am Chamkilo. I am Chamkilo. I am Chamkilo. I am well. I am well. I am well. I am well. I am well. ",
      'image': "https://cdn.inquisitr.com/wp-content/uploads/2020/01/One-Piece-Straw-Hat-Pirates-bounties-1.jpg",
      'likes': 0,
      'comment': 0,
      'shares': 0,
    },
    {
      'id':"5",
      'name': "Bipul Adhikari",
      'day': "Yesterday",
      'time': "11:11 PM",
      'status': "Jhapali gafadi Jhapali gafadi Jhapali gafadi Jhapali gafadi Jhapali gafadi Jhapali gafadi ",
      'image': "https://cdn.inquisitr.com/wp-content/uploads/2020/01/One-Piece-Straw-Hat-Pirates-bounties-1.jpg",
      'likes': 0,
      'comment': 0,
      'shares': 0,
    },
  ];
}